- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Add nginx configuration
  copy:
    src: ./templates/first.conf
    dest: /etc/nginx/sites-available/first.conf

- name: Enable website configuration
  file:
    src: /etc/nginx/sites-available/first.conf
    dest: /etc/nginx/sites-enabled/first.conf
    state: link

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: nginx enabled
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes