- name: create directory
  file:
    path: "/var/www/html/images"
    state: directory

- name: copy files
  copy:
    src: "./templates/static.zip"
    dest: "/var/www/html/images"

- name: Unzip files
  unarchive:
    src: "/var/www/html/images/static.zip"
    dest: "/var/www/html/images/"
    remote_src: yes

